export {
  GET_INMATE_START,
  GET_INMATE_SUCCESS,
  GET_INMATE_ERROR,
  ADD_INMATE_START,
  ADD_INMATE_ERROR,
  ADD_INMATE_SUCCESS,
  DELETE_INMATE_START,
  DELETE_INMATE_ERROR,
  DELETE_INMATE_SUCCESS
} from "./Prisoners";
