export {
  GET_INMATE_START,
  GET_INMATE_SUCCESS,
  GET_INMATE_ERROR,
  ADD_INMATE_START,
  ADD_INMATE_ERROR,
  ADD_INMATE_SUCCESS,
  DELETE_INMATE_START,
  DELETE_INMATE_ERROR,
  DELETE_INMATE_SUCCESS,
  UPDATE_INMATE_ERROR,
  UPDATE_INMATE_START,
  UPDATE_INMATE_SUCCESS
} from "./Prisoners";

export {
  GET_PRISON_START,
  GET_PRISON_SUCCESS,
  GET_PRISON_ERROR,
  ADD_PRISON_START,
  ADD_PRISON_ERROR,
  ADD_PRISON_SUCCESS,
  DELETE_PRISON_START,
  DELETE_PRISON_ERROR,
  DELETE_PRISON_SUCCESS
} from "./Prisons";






export {
LOGIN_START,LOGIN_FAILURE,LOGIN_SUCCESS
} from "./Login";
